create database villagers;

use villagers;

create table villagerList(bezeichnung varchar(30), species varchar (30), gender varchar(10), personality varchar(30));

insert into villagerList (bezeichnung, species, gender, personality) values
("Ace","Bird","Male","Jock"),
("Admiral","Bird","Male","Cranky"),
("Agent S","Squirrel","Female","Peppy"),
("Agnes","Pig","Female","Big sister"),
("Aisle","Bear cub","Male","Lazy"),
("Al","Gorilla","Male","Lazy"),
("Alfonso","Alligator","Male","Lazy"),
("Alice","Koala","Female","Normal"),
("Alli","Alligator","Female","Snooty"),
("Amelia","Eagle","Female","Snooty"),
("Anabelle","Anteater","Female","Peppy"),
("Analog","Penguin","Male","Jock"),
("Anchovy","Bird","Male","Lazy"),
("Angus","Bull","Male","Cranky"),
("Anicotti","Mouse","Female","Peppy"),
("Ankha","Cat","Female","Snooty"),
("Annalisa","Anteater","Female","Normal"),
("Annalise","Horse","Female","Snooty"),
("Antonio","Anteater","Male","Jock"),
("Apollo","Eagle","Male","Cranky"),
("Apple","Hamster","Female","Peppy"),
("Astrid","Kangaroo","Female","Snooty"),
("Audie","Wolf","Female","Peppy"),
("Aurora","Penguin","Female","Normal"),
("Ava","Chicken","Female","Normal"),
("Avery","Eagle","Male","Cranky"),
("Axel","Elephant","Male","Jock"),
("Azalea","Rhinoceros","Female","Snooty"),
("Aziz","Lion","Male","Jock"),
("Baabara","Sheep","Female","Snooty"),
("Bam","Deer","Male","Jock"),
("Bangle","Tiger","Female","Peppy"),
("Barold","Bear cub","Male","Lazy"),
("Bea","Dog","Female","Normal"),
("Beardo","Bear","Male","Smug"),
("Beau","Deer","Male","Lazy"),
("Becky","Chicken","Female","Snooty"),
("Bella","Mouse","Female","Peppy"),
("Belle","Cow","Female","Peppy"),
("Benedict","Chicken","Male","Lazy"),
("Benjamin","Dog","Male","Lazy"),
("Bertha","Hippo","Female","Normal"),
("Bessie","Cow","Female","Normal"),
("Bettina","Mouse","Female","Normal"),
("Betty","Chicken","Female","Normal"),
("Bianca","Tiger","Female","Peppy"),
("Biff","Hippo","Male","Jock"),
("Big Top","Elephant","Male","Lazy"),
("Bill","Duck","Male","Jock"),
("Billy","Goat","Male","Jock"),
("Biskit","Dog","Male","Lazy"),
("Bitty","Hippo","Female","Snooty"),
("Blaire","Squirrel","Female","Snooty"),
("Blanche","Ostrich","Female","Snooty"),
("Bluebear","Bear cub","Female","Peppy"),
("Bob","Cat","Male","Lazy"),
("Bonbon","Rabbit","Female","Peppy"),
("Bones","Dog","Male","Lazy"),
("Boomer","Penguin","Male","Lazy"),
("Boone","Gorilla","Male","Jock"),
("Boots","Alligator","Male","Jock"),
("Boris","Pig","Male","Cranky"),
("Bow","Dog","Male","Lazy"),
("Boyd","Gorilla","Male","Cranky"),
("Bree","Mouse","Female","Snooty"),
("Broccolo","Mouse","Male","Lazy"),
("Broffina","Chicken","Female","Snooty"),
("Bruce","Deer","Male","Cranky"),
("Bubbles","Hippo","Female","Peppy"),
("Buck","Horse","Male","Jock"),
("Bud","Lion","Male","Jock"),
("Bunnie","Rabbit","Female","Peppy"),
("Butch","Dog","Male","Cranky"),
("Buzz","Eagle","Male","Cranky"),
("Cally","Squirrel","Female","Normal"),
("Camofrog","Frog","Male","Cranky"),
("Canberra","Koala","Female","Big sister"),
("Candi","Mouse","Female","Peppy"),
("Carmen (Mouse)","Mouse","Female","Snooty"),
("Carmen (Rabbit)","Rabbit","Female","Peppy"),
("Caroline","Squirrel","Female","Normal"),
("Carrie","Kangaroo","Female","Normal"),
("Carrot","Cow","Female","Normal"),
("Cashmere","Sheep","Female","Snooty"),
("Cece","Squirrel","Female","Peppy"),
("Celia","Eagle","Female","Normal"),
("Cephalobot","Octopus","Male","Smug"),
("Cesar","Gorilla","Male","Cranky"),
("Chabwick","Penguin","Male","Lazy"),
("Chadder","Mouse","Male","Smug"),
("Chai","Elephant","Female","Peppy"),
("Champ","Monkey","Male","Jock"),
("Charlise","Bear","Female","Big sister "),
("Chelsea","Deer","Female","Normal"),
("Cheri","Bear cub","Female","Peppy"),
("Cherry","Dog","Female","Big sister"),
("Chester","Bear cub","Male","Lazy"),
("Chevre","Goat","Female","Normal"),
("Chico","Mouse","Male","Lazy"),
("Chief","Wolf","Male","Cranky"),
("Chops","Pig","Male","Smug"),
("Chow","Bear","Male","Cranky"),
("Chrissy","Rabbit","Female","Peppy"),
("Chuck","Bull","Male","Cranky"),
("Clara","Hippo","Female","Normal"),
("Claude","Rabbit","Male","Lazy"),
("Claudia","Tiger","Female","Snooty"),
("Clay","Hamster","Male","Lazy"),
("Cleo","Horse","Female","Snooty"),
("Clyde","Horse","Male","Lazy"),
("Coach","Bull","Male","Jock"),
("Cobb","Pig","Male","Jock"),
("Coco","Rabbit","Female","Normal"),
("Cole","Rabbit","Male","Lazy"),
("Colton","Horse","Male","Smug"),
("Cookie","Dog","Female","Peppy"),
("Cousteau","Frog","Male","Jock"),
("Cranston","Ostrich","Male","Lazy"),
("Croque","Frog","Male","Cranky"),
("Cube","Penguin","Male","Lazy"),
("Cupcake","Bear cub","Female","Snooty"),
("Curlos","Sheep","Male","Smug "),
("Curly","Pig","Male","Jock"),
("Curt","Bear","Male","Cranky"),
("Cyd","Elephant","Male","Cranky"),
("Cyrano","Anteater","Male","Cranky"),
("Daisy","Dog","Female","Normal"),
("Deena","Duck","Female","Normal"),
("Deirdre","Deer","Female","Big sister"),
("Del","Alligator","Male","Cranky"),
("Deli","Monkey","Male","Lazy"),
("Derwin","Duck","Male","Lazy"),
("Diana","Deer","Female","Snooty"),
("Diva","Frog","Female","Big sister"),
("Dizzy","Elephant","Male","Lazy"),
("Dobie","Wolf","Male","Cranky "),
("Doc","Rabbit","Male","Lazy"),
("Dom","Sheep","Male","Jock"),
("Dora","Mouse","Female","Normal"),
("Dotty","Rabbit","Female","Peppy"),
("Dozer","Bear","Male","Lazy"),
("Drago","Alligator","Male","Lazy"),
("Drake","Duck","Male","Lazy"),
("Drift","Frog","Male","Jock"),
("Ed","Horse","Male","Smug "),
("Egbert","Chicken","Male","Lazy"),
("Elina","Elephant","Female","Peppy"),
("Elise","Monkey","Female","Snooty"),
("Ellie","Elephant","Female","Normal"),
("Elmer","Horse","Male","Lazy"),
("Eloise","Elephant","Female","Snooty"),
("Elvis","Lion","Male","Cranky"),
("Emerald","Frog","Female","Normal"),
("Epona","Horse","Female","Peppy"),
("Erik","Deer","Male","Lazy"),
("Étoile","Sheep","Female","Normal"),
("Eugene","Koala","Male","Smug"),
("Eunice","Sheep","Female","Normal"),
("Faith","Koala","Female","Big sister "),
("Fang","Wolf","Male","Cranky"),
("Fauna","Deer","Female","Normal"),
("Felicity","Cat","Female","Peppy"),
("Felyne","Cat","Male","Lazy"),
("Filbert","Squirrel","Male","Lazy"),
("Filly","Horse","Female","Normal"),
("Flash","Bird","Male","Cranky"),
("Flip","Monkey","Male","Jock"),
("Flo","Penguin","Female","Big sister"),
("Flora","Ostrich","Female","Peppy"),
("Flossie","Mouse","Female","Peppy"),
("Flurry","Hamster","Female","Normal"),
("Francine","Rabbit","Female","Snooty"),
("Frank","Eagle","Male","Cranky"),
("Freckles","Duck","Female","Peppy"),
("Frett","Dog","Male","Cranky"),
("Freya","Wolf","Female","Snooty"),
("Friga","Penguin","Female","Snooty"),
("Frita","Sheep","Female","Big sister"),
("Frobert","Frog","Male","Jock"),
("Fruity","Duck","Male","Jock"),
("Fuchsia","Deer","Female","Big sister"),
("Gabi","Rabbit","Female","Peppy"),
("Gala","Pig","Female","Normal"),
("Ganon","Pig","Male","Cranky"),
("Gaston","Rabbit","Male","Cranky"),
("Gayle","Alligator","Female","Normal"),
("Gen","Sheep","Male","Jock"),
("Genji","Rabbit","Male","Jock"),
("Gigi","Frog","Female","Snooty"),
("Gladys","Ostrich","Female","Normal"),
("Gloria","Duck","Female","Snooty"),
("Goldie","Dog","Female","Normal"),
("Gonzo","Koala","Male","Cranky"),
("Goose","Chicken","Male","Jock"),
("Graham","Hamster","Male","Smug"),
("Greta","Mouse","Female","Snooty"),
("Grizzly","Bear","Male","Cranky"),
("Groucho","Bear","Male","Cranky"),
("Gruff","Goat","Male","Cranky"),
("Gwen","Penguin","Female","Snooty"),
("Hambo","Pig","Male","Jock"),
("Hamlet","Hamster","Male","Jock"),
("Hamphrey","Hamster","Male","Cranky"),
("Hank","Chicken","Male","Jock"),
("Hans","Gorilla","Male","Smug"),
("Harry","Hippo","Male","Cranky "),
("Hazel","Squirrel","Female","Big sister"),
("Hector","Chicken","Male","Jock"),
("Henry","Frog","Male","Smug"),
("Hippeux","Hippo","Male","Smug"),
("Holden","Hamster","Male","Jock"),
("Hopkins","Rabbit","Male","Lazy"),
("Hopper","Penguin","Male","Cranky"),
("Hornsby","Rhinoceros","Male","Lazy"),
("Huck","Frog","Male","Smug "),
("Huggy","Koala","Female","Peppy"),
("Hugh","Pig","Male","Lazy"),
("Iggly","Penguin","Male","Jock"),
("Iggy","Goat","Male","Jock"),
("Ike","Bear","Male","Cranky"),
("Inkwell","Octopus","Male","Jock"),
("Ione","Squirrel","Female","Normal"),
("Jacob","Bird","Male","Lazy"),
("Jacques","Bird","Male","Smug"),
("Jambette","Frog","Female","Normal"),
("Jane","Gorilla","Female","Snooty"),
("Jay","Bird","Male","Jock"),
("Jeremiah","Frog","Male","Lazy"),
("Jitters","Bird","Male","Jock"),
("Joe","Bird","Male","Cranky"),
("Joey","Duck","Male","Lazy"),
("Jūbei","Lion","Male","Cranky"),
("Judy","Bear cub","Female","Snooty"),
("Julia","Ostrich","Female","Snooty"),
("Julian","Horse","Male","Smug"),
("June","Bear cub","Female","Normal"),
("Kabuki","Cat","Male","Cranky"),
("Katt","Cat","Female","Big sister"),
("Keaton","Eagle","Male","Smug"),
("Ken","Chicken","Male","Smug"),
("Ketchup","Duck","Female","Peppy"),
("Kevin","Pig","Male","Jock"),
("Kid Cat","Cat","Male","Jock"),
("Kidd","Goat","Male","Smug "),
("Kiki","Cat","Female","Normal"),
("Kit","Squirrel","Male","Jock"),
("Kitt","Kangaroo","Female","Normal"),
("Kitty","Cat","Female","Snooty"),
("Klaus","Bear","Male","Smug"),
("Knox","Chicken","Male","Cranky"),
("Kody","Bear cub","Male","Jock"),
("Koharu","Kangaroo","Female","Peppy"),
("Kyle","Wolf","Male","Smug"),
("Leigh","Chicken","Female","Peppy"),
("Leonardo","Tiger","Male","Jock"),
("Leopold","Lion","Male","Smug "),
("Lily","Frog","Female","Normal"),
("Limberg","Mouse","Male","Cranky"),
("Lionel","Lion","Male","Smug"),
("Liz","Alligator","Female","Normal"),
("Lobo","Wolf","Male","Cranky"),
("Lolly","Cat","Female","Normal"),
("Lopez","Deer","Male","Smug"),
("Louie","Gorilla","Male","Jock"),
("Lucha","Bird","Male","Smug"),
("Lucky","Dog","Male","Lazy"),
("Lucy","Pig","Female","Normal"),
("Lulu (Anteater)","Anteater","Female","Snooty"),
("Lulu (Hippo)","Hippo","Female","Peppy"),
("Lyman","Koala","Male","Jock"),
("Mac","Dog","Male","Jock"),
("Madam Rosa","Bird","Female","Snooty"),
("Maddie","Dog","Female","Peppy"),
("Maelle","Duck","Female","Snooty"),
("Maggie","Pig","Female","Normal"),
("Mallary","Duck","Female","Snooty"),
("Maple","Bear cub","Female","Normal"),
("Marcel","Dog","Male","Lazy"),
("Marcie","Kangaroo","Female","Normal"),
("Marcy","Kangaroo","Female","Peppy"),
("Margie","Elephant","Female","Normal"),
("Marina","Octopus","Female","Normal"),
("Marlo","Hamster","Male","Cranky"),
("Marshal","Squirrel","Male","Smug"),
("Marty","Bear cub","Male","Lazy"),
("Masa","Dog","Male","Jock"),
("Mathilda","Kangaroo","Female","Snooty"),
("Medli","Bird","Female","Normal"),
("Megan","Bear","Female","Normal"),
("Megumi","Dog","Female","Peppy"),
("Melba","Koala","Female","Normal"),
("Meow","Cat","Female","Peppy"),
("Merengue","Rhinoceros","Female","Normal"),
("Merry","Cat","Female","Peppy"),
("Midge","Bird","Female","Normal"),
("Mint","Squirrel","Female","Snooty"),
("Mira","Rabbit","Female","Big sister"),
("Miranda","Duck","Female","Snooty"),
("Mitzi","Cat","Female","Normal"),
("Moe","Cat","Male","Lazy"),
("Molly","Duck","Female","Normal"),
("Monique","Cat","Female","Snooty"),
("Monty","Monkey","Male","Cranky"),
("Moose","Mouse","Male","Jock"),
("Mott","Lion","Male","Jock"),
("Muffy","Sheep","Female","Big sister"),
("Murphy","Bear cub","Male","Cranky"),
("Nan","Goat","Female","Normal"),
("Nana","Monkey","Female","Normal"),
("Naomi","Cow","Female","Snooty"),
("Nate","Bear","Male","Lazy"),
("Nibbles","Squirrel","Female","Peppy"),
("Nindori","Ostrich","Male","Jock"),
("Norma","Cow","Female","Normal"),
("Nosegay","Anteater","Female","Normal"),
("Octavian","Octopus","Male","Cranky"),
("O'Hare","Rabbit","Male","Smug "),
("Olaf","Anteater","Male","Smug"),
("Olive","Bear cub","Female","Normal"),
("Olivia","Cat","Female","Snooty"),
("Opal","Elephant","Female","Snooty"),
("Otis","Bird","Male","Lazy"),
("Oxford","Bull","Male","Cranky"),
("Ozzie","Koala","Male","Lazy"),
("Pancetti","Pig","Female","Snooty"),
("Pango","Anteater","Female","Peppy"),
("Paolo","Elephant","Male","Lazy"),
("Papi","Horse","Male","Lazy"),
("Pashmina","Goat","Female","Big sister"),
("Pate","Duck","Female","Peppy"),
("Patricia","Rhinoceros","Female","Normal"),
("Patty","Cow","Female","Peppy"),
("Paula","Bear","Female","Big sister "),
("Peaches","Horse","Female","Normal"),
("Peanut","Squirrel","Female","Peppy"),
("Pecan","Squirrel","Female","Snooty"),
("Peck","Bird","Male","Jock"),
("Peewee","Gorilla","Male","Cranky"),
("Peggy","Pig","Female","Peppy"),
("Pekoe","Bear cub","Female","Normal"),
("Penelope","Mouse","Female","Peppy"),
("Penny","Mouse","Female","Peppy"),
("Petri","Mouse","Female","Snooty"),
("Petunia","Cow","Female","Snooty"),
("Phil","Ostrich","Male","Smug"),
("Phoebe","Ostrich","Female","Big sister"),
("Pierce","Eagle","Male","Jock"),
("Pierre","Cat","Male","Jock"),
("Pietro","Sheep","Male","Smug"),
("Pigleg","Pig","Male","Jock"),
("Pinky","Bear","Female","Peppy"),
("Piper","Bird","Female","Peppy"),
("Pippy","Rabbit","Female","Peppy"),
("Plucky","Chicken","Female","Big sister "),
("Poko","Bear cub","Male","Jock"),
("Pompom","Duck","Female","Peppy"),
("Poncho","Bear cub","Male","Jock"),
("Poppy","Squirrel","Female","Normal"),
("Portia","Dog","Female","Snooty"),
("Prince","Frog","Male","Lazy"),
("Puck","Penguin","Male","Lazy"),
("Puddles","Frog","Female","Peppy"),
("Pudge","Bear cub","Male","Lazy"),
("Punchy","Cat","Male","Lazy"),
("Purrl","Cat","Female","Snooty"),
("Queenie","Ostrich","Female","Snooty"),
("Quetzal","Eagle","Male","Jock"),
("Quillson","Duck","Male","Smug"),
("Quinn","Eagle","Female","Big sister"),
("Raddle","Frog","Male","Lazy"),
("Rasher","Pig","Male","Cranky"),
("Raymond","Cat","Male","Smug"),
("Renée","Rhinoceros","Female","Big sister"),
("Reneigh","Horse","Female","Big sister"),
("Rex","Lion","Male","Lazy"),
("Rhoda","Chicken","Female","Snooty"),
("Rhonda","Rhinoceros","Female","Normal"),
("Ribbot","Frog","Male","Jock"),
("Ricky","Squirrel","Male","Cranky"),
("Rilla","Gorilla","Female","Peppy"),
("Rio","Ostrich","Female","Peppy"),
("Rizzo","Mouse","Male","Cranky"),
("Roald","Penguin","Male","Jock"),
("Robin","Bird","Female","Snooty"),
("Rocco","Hippo","Male","Cranky"),
("Rocket","Gorilla","Female","Big sister"),
("Rod","Mouse","Male","Jock"),
("Rodeo","Bull","Male","Lazy"),
("Rodney","Hamster","Male","Smug"),
("Rolf","Tiger","Male","Cranky"),
("Rollo","Hippo","Male","Lazy"),
("Rooney","Kangaroo","Male","Cranky"),
("Rory","Lion","Male","Jock"),
("Roscoe","Horse","Male","Cranky"),
("Rosie","Cat","Female","Peppy"),
("Roswell","Alligator","Male","Smug "),
("Rowan","Tiger","Male","Jock "),
("Ruby","Rabbit","Female","Peppy"),
("Rudy","Cat","Male","Jock"),
("Sally","Squirrel","Female","Normal"),
("Samson","Mouse","Male","Jock"),
("Sandy","Ostrich","Female","Normal"),
("Sasha","Rabbit","Male","Lazy"),
("Savannah","Horse","Female","Normal"),
("Scoot","Duck","Male","Jock"),
("Shari","Monkey","Female","Big sister"),
("Sheldon","Squirrel","Male","Jock"),
("Shep","Dog","Male","Smug"),
("Sherb","Goat","Male","Lazy"),
("Shinabiru","Duck","Male","Jock"),
("Shino","Deer","Female","Peppy"),
("Shoukichi","Bird","Male","Jock"),
("Simon","Monkey","Male","Lazy"),
("Skye","Wolf","Female","Normal"),
("Sly","Alligator","Male","Jock"),
("Snake","Rabbit","Male","Jock"),
("Snooty","Anteater","Female","Snooty"),
("Soleil","Hamster","Female","Snooty"),
("Sparro","Bird","Male","Jock"),
("Spike","Rhinoceros","Male","Cranky"),
("Spork","Pig","Male","Lazy"),
("Sprinkle","Penguin","Female","Peppy"),
("Sprocket","Ostrich","Male","Jock"),
("Static","Squirrel","Male","Cranky"),
("Stella","Sheep","Female","Normal"),
("Sterling","Eagle","Male","Jock"),
("Stinky","Cat","Male","Jock"),
("Stitches","Bear cub","Male","Lazy"),
("Stu","Bull","Male","Lazy"),
("Sue E","Pig","Female","Snooty"),
("Sunny","Frog","Female","Normal"),
("Sven","Goat","Male","Lazy"),
("Sydney","Koala","Female","Normal"),
("Sylvana","Squirrel","Female","Normal"),
("Sylvia","Kangaroo","Female","Big sister "),
("T-Bone","Bull","Male","Cranky "),
("Tabby","Cat","Female","Peppy"),
("Tad","Frog","Male","Jock"),
("Tammi","Monkey","Female","Peppy"),
("Tammy","Bear cub","Female","Big sister"),
("Tangy","Cat","Female","Peppy"),
("Tank","Rhinoceros","Male","Jock"),
("Tarou","Wolf","Male","Jock"),
("Tasha","Squirrel","Female","Snooty"),
("Teddy","Bear","Male","Jock"),
("Tex","Penguin","Male","Smug"),
("Tia","Elephant","Female","Normal"),
("Tiansheng","Monkey","Male","Jock"),
("Tiara","Rhinoceros","Female","Snooty"),
("Tiffany","Rabbit","Female","Snooty"),
("Timbra","Sheep","Female","Snooty"),
("Tipper","Cow","Female","Snooty"),
("Toby","Rabbit","Male","Smug"),
("Tom","Cat","Male","Cranky"),
("Truffles","Pig","Female","Peppy"),
("Tucker","Elephant","Male","Lazy"),
("Tutu","Bear","Female","Peppy"),
("Twiggy","Bird","Female","Peppy"),
("Twirp","Bird","Male","Cranky"),
("Tybalt","Tiger","Male","Jock"),
("Ursala","Bear","Female","Big sister "),
("Valise","Kangaroo","Female","Snooty"),
("Velma","Goat","Female","Snooty"),
("Vesta","Sheep","Female","Normal"),
("Vic","Bull","Male","Cranky"),
("Viché","Squirrel","Female","Normal"),
("Victoria","Horse","Female","Peppy"),
("Violet","Gorilla","Female","Snooty "),
("Vivian","Wolf","Female","Snooty"),
("Vladimir","Bear cub","Male","Cranky"),
("W. Link","Wolf","Male","Smug"),
("Wade","Penguin","Male","Lazy"),
("Walker","Dog","Male","Lazy"),
("Walt","Kangaroo","Male","Cranky"),
("Wart Jr.","Frog","Male","Cranky"),
("Weber","Duck","Male","Lazy"),
("Weldon","Bull","Male","Cranky"),
("Wendy","Sheep","Female","Peppy"),
("Whitney","Wolf","Female","Snooty"),
("Willow","Sheep","Female","Snooty"),
("Winnie","Horse","Female","Peppy"),
("Wolfgang","Wolf","Male","Cranky"),
("Woolio","Sheep","Male","Jock"),
("Yodel","Gorilla","Male","Lazy"),
("Yuka","Koala","Female","Snooty"),
("Zell","Deer","Male","Smug"),
("Zoe","Anteater","Female","Normal"),
("Zucker","Octopus","Male","Lazy");
